## 강의 내용
### 수학 / 코드

- 수학기호 / LaTeX
- 선형대수 / NumPy
    - Linear Algebra
    - 데이터를 다루기 위한 '기술용어'
    - 복잡한 데이터 연산에 대한 소통을 간결하고 정확하게
- 함수와 미적부 / SymPy
    - Function and Calculus
    - 함수 : 데이터 분석의 결과와 품질을 표현하는 방법
    - 예측 문제 : 입력 데이터를 넣으면 원하는 출력 데이터를 만드는 함수 찾기
    - 미적분 : 함수의 특징을 기술하는 방법
- 최적화 / SciPy
    - Optimization
    - 최적화 : 가장 좋은 함수의 입력값 혹은 함수를 찾는 작업
    - 최적화에는 미분이 필수
- 확률론 / pgmpy (가장 중요하고 메인이 되는 부분)
    - 데이터 분석, 머신러닝은 데이터로부터 지식(명제)를 이끌어내는 작업
    - 지식(명제)의 참과 거짓을 다루는 것은 논리학
    - 고전 논리학에서 명제는 참(100% 진실) 또는 거짓(0% 진실)
    - 확률론에서는 명제는 숫자로 표현되는 진실성을 가진다. => 근대 논리학
    

`$\alpha$와 $\beta$의 값이 같다.`

$\alpha$와 $\beta$의 값이 같다.

`$$ \alpha = \beta $$`
$$ \alpha = \beta $$

$\alpha$는 alpha(알파)이다.

$\beta$는 beta(베타)이다.

$\gamma$는 gamma(감마)이다.

$\delta$는 delta(델타)이다.

$\epsilon$은 epsilon(엡실론)이다.

$\zeta$는 zeta(제타)이다.

$\eta$는 eta(에타)이다.

$\theta$는 theta(쎄타)이다.

$\kappa$는 kappa(카파)이다.

$\lambda$는 lambda(람다)이다.

$\mu$는 mu(뮤)이다.

$\nu$는 nu(누)이다.

$\xi$는 xi(크싸이)이다.

$\pi$는 pi(파이)이다.

$\rho$는 rho(로)이다.

$\sigma$는 sigma(시그마)이다.

$\tau$는 tau(타우)이다.

$\phi$는 phi(피)이다.

$\chi$는 chi(카이)이다.

$\psi$는 psi(프사이)이다.

$\omega$는 omega(오메가)이다.

$$ \alpha, \beta, \gamma, \delta, \epsilon, \zeta, \eta, \theta, \kappa, \lambda, \mu, \nu, \xi, \pi, \rho, \sigma, \tau, \phi, \chi, \psi, \omega $$

In [2]:
# scalar -> vector -> matrix -> tensor

In [3]:
from sklearn.datasets import load_iris

In [4]:
iris = load_iris()

In [11]:
# 첫번쨰 꽃의 모든 길이를 나타내라
x1 = iris.data[0, :]
x1

array([5.1, 3.5, 1.4, 0.2])

In [13]:
x2 = np.array(iris.data[1, :])
x2 = np.array([[4.9], [3.0], [1.4], [0.2]]) 
x2

array([[4.9],
       [3. ],
       [1.4],
       [0.2]])

In [15]:
X = np.array([
    [5.1, 3.5, 1.4, 0.2],
    [4.9, 3.0, 1.4, 0.2]
])
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2]])

In [17]:
x2.T

array([[4.9, 3. , 1.4, 0.2]])

In [20]:
X.T

array([[5.1, 4.9],
       [3.5, 3. ],
       [1.4, 1.4],
       [0.2, 0.2]])

In [21]:
X.T.T

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2]])

In [22]:
# 연습문제 2.1.4
# 영벡터, 일벡터, 정방행렬, 대각행렬, 항등행렬, 대칭행렬의 예를 하나씩 만들어본다.

In [47]:
#1. 영벡터
ex_1 = np.array([
    [0,0,0,0,0],
    [0,0,0,0,0],
    [0,0,0,0,0],
    [0,0,0,0,0],
    [0,0,0,0,0],
])
ex_1

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [26]:
# 1. 영벡터 NumPy
example_1 = np.zeros((5, 5))
example_1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [49]:
# 2. 일벡터
ex_2 = np.array([
    [1,1,1,1,1],
    [1,1,1,1,1],
    [1,1,1,1,1],
    [1,1,1,1,1],
    [1,1,1,1,1],
])
ex_2

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [29]:
# 2. 일벡터 NumPy
example_2 = np.ones((5, 5))
example_2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [44]:
#3. 정방행렬 NumPy
example3 = np.array([
    [1,2,3,5],
    [6,3,2,7],
    [1,6,8,3],
    [9,3,3,5]
])
example3

array([[1, 2, 3, 5],
       [6, 3, 2, 7],
       [1, 6, 8, 3],
       [9, 3, 3, 5]])

In [52]:
# 4. 대각행렬
ex_4 = np.array([
    [1,0,0],
    [0,2,0],
    [0,0,8],
])
ex_4

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 8]])

In [31]:
# 4. 대각행렬 NumPy
example_4 = np.diag([1, 2, 8])
example_4

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 8]])

In [54]:
# 5. 항등행렬
ex_5 = np.array([
    [1,0,0,0],
    [0,1,0,0],
    [0,0,1,0],
    [0,0,0,1],
])
ex_5

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [34]:
# 5. 항등행렬 NumPy
example_5a = np.identity(4)
example_5a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [36]:
example_5b = np.eye(4)
example_5b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [39]:
#6. 대칭행렬 NumPy
example_6 = np.array([
    [1, 2, 3],
    [2, 1, 2],
    [3, 2, 1]
])
example_6

array([[1, 2, 3],
       [2, 1, 2],
       [3, 2, 1]])

In [40]:
example_6.T

array([[1, 2, 3],
       [2, 1, 2],
       [3, 2, 1]])

In [ ]:
2. 위의 벡터와 행렬을 NumPy로 나타내 본다.