### 연습 문제 2.4.5

In [16]:
from sklearn.datasets import load_boston
boston = load_boston()
X = boston.data
y = boston.target
A = X[:4, [0, 4, 5, 6]]  # 'CRIM', 'NOX', 'RM', 'AGE'
b = y[:4]

In [17]:
A

array([[6.320e-03, 5.380e-01, 6.575e+00, 6.520e+01],
       [2.731e-02, 4.690e-01, 6.421e+00, 7.890e+01],
       [2.729e-02, 4.690e-01, 7.185e+00, 6.110e+01],
       [3.237e-02, 4.580e-01, 6.998e+00, 4.580e+01]])

In [18]:
b

array([24. , 21.6, 34.7, 33.4])

In [19]:
Ainv = np.linalg.inv(A)

In [20]:
x = np.dot(Ainv, b)

In [21]:
print(x)

[-3.12710043e+02 -1.15193942e+02  1.44996465e+01 -1.13259317e-01]


가중치 부호로부터 다음 사실을 알 수 있다. 집값은
- 범죄율(CRIM)에 반비례한다.
- 공기 오염도(NOX)에 반비례한다.
- 방의 개수(RM)에 비례한다.
- 오래된 정도(AGE)에 반비례한다.

### 연습 문제 2.4.6

In [67]:
from sklearn.datasets import load_boston
boston = load_boston()
X = boston.data
y = boston.target

In [68]:
x, resid, rank, s = np.linalg.lstsq(X, y)

C:\Users\Gk\anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


In [69]:
print(x)

[-9.28965170e-02  4.87149552e-02 -4.05997958e-03  2.85399882e+00
 -2.86843637e+00  5.92814778e+00 -7.26933458e-03 -9.68514157e-01
  1.71151128e-01 -9.39621540e-03 -3.92190926e-01  1.49056102e-02
 -4.16304471e-01]


In [1]:
# numpy를 사용한 역행렬 계산
A = np.array([[1, 1, 0], [0, 1, 1], [1, 1, 1]])
A

array([[1, 1, 0],
       [0, 1, 1],
       [1, 1, 1]])

In [2]:
Ainv = np.linalg.inv(A)
Ainv

array([[ 0., -1.,  1.],
       [ 1.,  1., -1.],
       [-1.,  0.,  1.]])

In [4]:
b = np.array([[2], [2], [3]])
b

array([[2],
       [2],
       [3]])

In [5]:
x = Ainv @ b
x

array([[1.],
       [1.],
       [1.]])

In [6]:
A @ x - b

array([[0.],
       [0.],
       [0.]])

In [7]:
x, resid, rank, s = np.linalg.lstsq(A, b)
x

C:\Users\Gk\anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


array([[1.],
       [1.],
       [1.]])

In [10]:
A = np.array([[1, 1, 0], [0, 1, 1], [1, 1, 1], [1, 1, 2]])
A

array([[1, 1, 0],
       [0, 1, 1],
       [1, 1, 1],
       [1, 1, 2]])

In [12]:
b = np.array([[2], [2], [3], [4.1]])
b

array([[2. ],
       [2. ],
       [3. ],
       [4.1]])

In [14]:
Apinv = np.linalg.inv(A.T @ A) @ A.T # 의사역행렬
Apinv

array([[ 0.33333333, -1.        ,  0.33333333,  0.33333333],
       [ 0.5       ,  1.        ,  0.        , -0.5       ],
       [-0.5       ,  0.        ,  0.        ,  0.5       ]])

In [16]:
x = Apinv @ b
x

array([[1.03333333],
       [0.95      ],
       [1.05      ]])

In [17]:
A @ x

array([[1.98333333],
       [2.        ],
       [3.03333333],
       [4.08333333]])

In [18]:
b

array([[2. ],
       [2. ],
       [3. ],
       [4.1]])

In [19]:
x, resid, rank, s = np.linalg.lstsq(A, b)
x

C:\Users\Gk\anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


array([[1.03333333],
       [0.95      ],
       [1.05      ]])

In [21]:
resid, np.linalg.norm(A @ x - b) ** 2

(array([0.00166667]), 0.0016666666666666698)