In [1]:
A = np.array([[1, -2], [2, -3]])
w1, V1 = np.linalg.eig(A)

print(w1)
print(V1)

[-0.99999998 -1.00000002]
[[0.70710678 0.70710678]
 [0.70710678 0.70710678]]


In [2]:
B = np.array([[2, 3], [2, 1]])
w2, V2 = np.linalg.eig(B)

print(w2)
print(V2)

[ 4. -1.]
[[ 0.83205029 -0.70710678]
 [ 0.5547002   0.70710678]]


In [4]:
C = np.array([[0, -1], [1, 0]])
w3, V3 = np.linalg.eig(C)

print(w3)
print(V3)

[0.+1.j 0.-1.j]
[[0.70710678+0.j         0.70710678-0.j        ]
 [0.        -0.70710678j 0.        +0.70710678j]]


In [6]:
D = np.array([[2, 1], [1, 2]])
w4, V4 = np.linalg.eig(D)

print(w4)
print(V4)

[3. 1.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [7]:
E = np.array([[2, 3], [2, 1]])
w5, V5 = np.linalg.eig(E)

print(w5)
print(V5)

[ 4. -1.]
[[ 0.83205029 -0.70710678]
 [ 0.5547002   0.70710678]]


In [8]:
F = np.array([[1, 1], [0, 1]])
w6, V6 = np.linalg.eig(F)

print(w6)
print(V6)

[1. 1.]
[[ 1.00000000e+00 -1.00000000e+00]
 [ 0.00000000e+00  2.22044605e-16]]


In [9]:
V2

array([[ 0.83205029, -0.70710678],
       [ 0.5547002 ,  0.70710678]])

In [10]:
V2_inv = np.linalg.inv(V2)
V2_inv

array([[ 0.72111026,  0.72111026],
       [-0.56568542,  0.84852814]])

In [18]:
V2 @ np.diag(w2) @ V2_inv

array([[2., 3.],
       [2., 1.]])

In [21]:
G = np.array([[1, 1], [0, 1]])
w7, V7 = np.linalg.eig(G)
print(w7)
print(V7)

[1. 1.]
[[ 1.00000000e+00 -1.00000000e+00]
 [ 0.00000000e+00  2.22044605e-16]]


In [22]:
V7

array([[ 1.00000000e+00, -1.00000000e+00],
       [ 0.00000000e+00,  2.22044605e-16]])

In [23]:
V7_inv = np.linalg.inv(V7)
V7_inv

array([[1.00000000e+00, 4.50359963e+15],
       [0.00000000e+00, 4.50359963e+15]])

In [24]:
V7 @ np.diag(w7) @ V7_inv

array([[1., 0.],
       [0., 1.]])