In [15]:
# 연습 문제 3.4.1

from numpy.linalg import svd

A = np.array([[3, 2, 2], [2, 3, -2]])
U, S, VT = svd(A)

array([[ 3,  2,  2],
       [ 2,  3, -2]])

In [16]:
U

array([[-0.70710678, -0.70710678],
       [-0.70710678,  0.70710678]])

In [17]:
S # 고윳값 같은건가?

array([5., 3.])

In [29]:
np.diag(S, 1)[:, 1:]

array([[5., 0.],
       [0., 3.],
       [0., 0.]])

In [19]:
VT

array([[-7.07106781e-01, -7.07106781e-01, -5.55111512e-17],
       [-2.35702260e-01,  2.35702260e-01, -9.42809042e-01],
       [-6.66666667e-01,  6.66666667e-01,  3.33333333e-01]])

In [22]:
U @ np.diag(S, 1)[:, 1:] @ VT

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [23]:
# 축소형 구하기
U2, S2, VT2 = svd(A, full_matrices=False)

In [24]:
U2

array([[-0.70710678, -0.70710678],
       [-0.70710678,  0.70710678]])

In [25]:
S2

array([5., 3.])

In [26]:
VT2

array([[-7.07106781e-01, -7.07106781e-01, -5.55111512e-17],
       [-2.35702260e-01,  2.35702260e-01, -9.42809042e-01]])

In [27]:
U2 @ np.diag(S2) @ VT2

array([[ 3.,  2.,  2.],
       [ 2.,  3., -2.]])

In [30]:
A = np.array([[2, 4], [1, 3], [0, 0], [0, 0]])
U2, S2, VT2 = svd(A, full_matrices=False)
U2 @ np.diag(S2) @ VT2

array([[2., 4.],
       [1., 3.],
       [0., 0.],
       [0., 0.]])