In [12]:
# f(x_1, x_2) = x_1 ** 2 + x_2 ** 2
# g(x_1, x_2) = x_1 + x_2 - 1 = 0

def f1array(x): # 목적함수
    return x[0] ** 2 + x[1] ** 2

def eq_constraint(x): # 제한조건
    return x[0] + x[1] - 1

sp.optimize.fmin_slsqp(f1array, np.array([1, 1]), eqcons=[eq_constraint])

# lambda 값은 못 구하는건지?

Optimization terminated successfully.    (Exit mode 0)
            Current function value: 0.5000000000000002
            Iterations: 2
            Function evaluations: 8
            Gradient evaluations: 2


array([0.5, 0.5])

In [14]:
# f(x_1, x_2) = x[0] + [1]
# g(x_1, x_2) = x[0] ** 2 + x[1] ** 2 - 1

def f2array(x): # 목적 함수
    return x[0] + x[1]

def eq_constraint2(x): # 제한 조건
    return x[0] ** 2 + x[1] ** 2 - 1

sp.optimize.fmin_slsqp(f2array, np.array([1, 1]), eqcons=[eq_constraint2])


Optimization terminated successfully.    (Exit mode 0)
            Current function value: 1.4142135623747087
            Iterations: 5
            Function evaluations: 20
            Gradient evaluations: 5


array([0.70710678, 0.70710678])

In [20]:
# 왜 sqrt인지?
def f2(x):
    return np.sqrt((x[0] - 4) ** 2 + (x[1] - 2) ** 2)

# 제한 조건 상수
k = 1
def ieq_constraint(x):
    return np.atleast_1d(k - np.sum(np.abs(x)))

sp.optimize.fmin_slsqp(f2, np.array([0, 0]), ieqcons=[ieq_constraint])

Optimization terminated successfully.    (Exit mode 0)
            Current function value: 3.605551280732028
            Iterations: 11
            Function evaluations: 77
            Gradient evaluations: 11


array([9.99999981e-01, 1.89941792e-08])