어떤 공장에서 두가지 제품을 생산해야 한다고 하자.
- 제품 A와 제품 B 각각 100개 이상 생산해야 한다.

x1 >= 100, x2 >= 100

- 시간은 500시간 밖에 없다.
- 제품 A는 생산하는데 1시간이 걸리고 제품 B는 2시간이 걸린다.

x1 + 2 * x2 <= 500

- 특정 부품이 9800개 밖에 없다.
- 제품 A는 생산하는데 특정 부품을 4개 필요로 하고 제품 B는 생산하는데 특정 부품을 5개 필요로 한다.

4 * x1 + 5 * x2 <= 9800

- 제품 A의 이익은 하나당 3만원이고 제품 B의 이익은 하나당 5만원이다.

arg max 3 * x1 + 5 * x2 

### 최소화하려는 목적함수

-> arg min -3 * x1 - 5 * x2

### 제한조건

-x1 <= -100

-x2 <= -100

##### 왜 위에 둘만 -1을 곱하는건지? 모든 제한조건에 동일하게 곱해줘야하는 것이 아닌지?


x1 + 2*x2 <= 500

4 * x1 + 5 * x2 <= 9800

x1 >= 0, x2 >= 0

In [27]:
c = np.array([-3, -5]) # 목적함수의 계수 벡터
A = np.array([[-1, 0], [0, -1], [1, 2], [4, 5]])
b = np.array([ [-100], [-100], [500], [9800] ])
#b = np.array([-100, -100, 500, 9800])
# 위 둘 b의 차이
# 만약 4 x 1 벡터일 경우 어떻게 쓰는게 맞는건지?

In [28]:
c

array([-3, -5])

In [29]:
A

array([[-1,  0],
       [ 0, -1],
       [ 1,  2],
       [ 4,  5]])

In [30]:
b

array([[-100],
       [-100],
       [ 500],
       [9800]])

In [31]:
sp.optimize.linprog(c, A, b)

     con: array([], dtype=float64)
     fun: -1399.999994807384
 message: 'Optimization terminated successfully.'
     nit: 6
   slack: array([1.99999991e+02, 4.19920389e-06, 3.31137414e-07, 8.10000001e+03])
  status: 0
 success: True
       x: array([299.99999127, 100.0000042 ])

In [37]:
import cvxpy as cp

# 변수의 정의
a = cp.Variable() # A의 생산량
b = cp.Variable() # B의 생산량

# 조건의 정의
constraints = [
    a >= 100, # A를 100개 이상 생산해야 한다.
    b >= 100, # B를 100개 이상 생산해야 한다.
    a + 2 * b <= 500, # 500시간 내에 생산해야 한다.
    4 * a + 5 * b <= 9800, # 부품이 9800개 밖에 없다.
]

# 문제의 정의
obj = cp.Maximize(3 * a + 5 * b)
prob = cp.Problem(obj, constraints)

# 계산
prob.solve()

# 결과
print("상태:", prob.status)
print("최적값:", a.value, b.value)

상태: optimal
최적값: 299.99999911572195 100.00000058337798


In [39]:
from cvxopt import matrix, solvers

Q = matrix(np.diag([2.0, 2.0]))
c = matrix(np.array([0.0, 0.0]))
A = matrix(np.array([[1.0, 1.0]]))
b = matrix(np.array([1.0]))

sol = solvers.qp(Q, c, A=A, b=b)
np.array(sol['x'])

array([[0.5],
       [0.5]])