In [1]:
N = 100
mu_0 = 0.5
np.random.seed(0)
x = sp.stats.bernoulli(mu_0).rvs(N)
n = np.count_nonzero(x)

sp.stats.binom_test(n, N)

0.9204107626128206

In [ ]:
N1 = 10
pvalues1 = np.array([sp.stats.binom_test(n, N1) for n in range(N1 + 1)])
fair_range1, = np.where(pvalues1 > 0.1)
fair_start1, fair_end1 = fair_range1[0], fair_range1[-1]
print("N={}일 떄 공정한 경우: 앞면이 나온 횟수가 {}~{}일 때".format(N1, fair_start1, fair_end1))

### 연습 문제 9.5.3

In [4]:
pvalues = []
N_range = range(1050, 1180)
for N in N_range:
    n = int(round(0.7 * N))
    pvalues.append(sp.stats.binom_test(n, N, p=2/3, alternative="greater"))

plt.plot(N_range, pvalues, "ro-")
plt.hlines(y=0.01, xmin=1050, xmax=1180, ls"--")
plt.xlim(1050, 1180)

In [5]:
sp.stats.binom_test(7, 10, p=2/3)

1.0

In [6]:
sp.stats.binom_test(70, 100, p=2/3)

0.5254485694755825

In [7]:
sp.stats.binom_test(700, 1000, p=2/3)

0.026789055469524904

In [8]:
sp.stats.binom_test(1400, 2000, p=2/3)

0.0014789302778934396

### 검정

표본조사를 한 1000명 중 520명이 찬성하였다. 전체 인구가 찬성이 더 많다고 말할 수 있는가?

- 귀무가설은?
- 

In [11]:
sp.stats.binom_test(520, 1000, 0.5, "greater")

0.10872414660212008

### 이항검정

1000가구 표본조사에서 40가구가 시청하고 있다. 시청율이 5%라고 할 수 있는가?(유의수준 5%)

In [12]:
# 16%는 유의수준 5%보다 높기에 가능 
sp.stats.binom_test(40, 1000, 0.05)

0.1673687516416663

In [13]:
sp.stats.binom_test(40, 1000, 0.05, "greater")

0.940185120948055

In [14]:
sp.stats.binom_test(40, 1000, 0.06)

0.006228851957544925

In [15]:
sp.stats.binom_test(40, 1000, 0.055)

0.037161212756091064

In [16]:
sp.stats.binom_test(40, 1000, 0.052)

0.10072229577376386

In [21]:
sp.stats.binom_test(40, 1000, 0.028)

0.026927372339543097

In [22]:
sp.stats.chisquare([9,8,12,11,9,11],[10,10,10,10,10,10])

Power_divergenceResult(statistic=1.2000000000000002, pvalue=0.9448773650021219)

In [23]:
sp.stats.chisquare([0,0,0,0,0,5])

Power_divergenceResult(statistic=25.000000000000004, pvalue=0.00013933379118562602)

In [24]:
obs = np.array([[105, 95], [100, 100]])
sp.stats.chi2_contingency(obs)

(0.16010006253908693,
 0.6890644083691786,
 1,
 array([[102.5,  97.5],
        [102.5,  97.5]]))

In [25]:
obs = np.array([[1050, 950], [1000, 1000]])
sp.stats.chi2_contingency(obs)

(2.4025015634771734,
 0.12114139495171163,
 1,
 array([[1025.,  975.],
        [1025.,  975.]]))

In [26]:
obs = np.array([[10500, 9500], [10000, 10000]])
sp.stats.chi2_contingency(obs)

(24.915672295184493,
 5.989353816039278e-07,
 1,
 array([[10250.,  9750.],
        [10250.,  9750.]]))