### Summary
- numpy : 선형대수를 빠르게 연산해주는 패키지
- 행열의 생성 1 : ndarray, np.array(iterable)
- 행열의 생성 2 : ones, zeros
- 행열 데이터 선택 : array[x, y, z]
- 행열 데이터 수정
    - 행열 데이터를 선택
    - =, > (값(scala, vector, matrix))
    - 브로드 캐스팅 개념
- arange : list에서 사용하는 range : 결과가 ndarray

### Quiz
- 100 ~ 130까지 랜덤한 숫자를 가지느 8*8 행렬을 만들고,
- 3의 배수는 fiz, 5의 배수는 buz, 3과 5의 배수는 fbz 문자로 변환
- 랜덤한 행렬 데이터
```
datas = np.random.randint(100, 130, size = (8, 8))
```
- 데이터 타입이 정수 -> 문자열 : ndarray.astype()


In [2]:
import numpy as np

In [40]:
datas = np.random.randint(100, 130, size = (8, 8))
datas

array([[128, 112, 126, 102, 128, 126, 116, 110],
       [122, 117, 124, 119, 126, 123, 105, 114],
       [109, 108, 127, 115, 112, 121, 107, 106],
       [121, 129, 129, 102, 113, 100, 111, 100],
       [118, 116, 103, 121, 108, 127, 114, 115],
       [112, 100, 102, 103, 127, 124, 124, 120],
       [125, 115, 113, 113, 117, 119, 102, 107],
       [120, 107, 103, 107, 106, 101, 105, 113]])

In [46]:
numA = 8
numB = 8

datas1 = datas.astype(str)
# datas[1,1].astype(int)

for a in range(0, numA):
    for b in range(0, numB):
        if not datas1[a, b].astype(int) % 15:
            datas1[a, b] = "fbz"
        elif not datas1[a, b].astype(int) % 3:
            datas1[a, b] = "fiz"
        elif not datas1[a, b].astype(int) % 5:
            datas1[a, b] = "buz"
        
        print(datas1[a, b], end='\t')
    print("")
    numA +=1

128	112	fiz	fiz	128	fiz	116	buz	
122	fiz	124	119	fiz	fiz	fbz	fiz	
109	fiz	127	buz	112	121	107	106	
121	fiz	fiz	fiz	113	buz	fiz	buz	
118	116	103	121	fiz	127	fiz	buz	
112	buz	fiz	103	127	124	124	fbz	
buz	buz	113	113	fiz	119	fiz	107	
fbz	107	103	107	106	101	fbz	113	


In [50]:
#3의 배수, 5의 배수, 15의 배수 위치값에 대한 T, F matrix 생성
datas % 3

array([[2, 1, 0, 0, 2, 0, 2, 2],
       [2, 0, 1, 2, 0, 0, 0, 0],
       [1, 0, 1, 1, 1, 1, 2, 1],
       [1, 0, 0, 0, 2, 1, 0, 1],
       [1, 2, 1, 1, 0, 1, 0, 1],
       [1, 1, 0, 1, 1, 1, 1, 0],
       [2, 1, 2, 2, 0, 2, 0, 2],
       [0, 2, 1, 2, 1, 2, 0, 2]], dtype=int32)

In [51]:
datas % 3 == 0

array([[False, False,  True,  True, False,  True, False, False],
       [False,  True, False, False,  True,  True,  True,  True],
       [False,  True, False, False, False, False, False, False],
       [False,  True,  True,  True, False, False,  True, False],
       [False, False, False, False,  True, False,  True, False],
       [False, False,  True, False, False, False, False,  True],
       [False, False, False, False,  True, False,  True, False],
       [ True, False, False, False, False, False,  True, False]])

In [53]:
idx_3 = datas % 3 == 0
idx_5 = datas % 5 == 0
idx_15 = datas % 15 == 0

In [54]:
# 데이터의 타입을 str으로 변환
datas2 = datas.copy()

In [55]:
datas2.dtype

dtype('int32')

In [56]:
result = datas2.astype("str")
result

array([['128', '112', '126', '102', '128', '126', '116', '110'],
       ['122', '117', '124', '119', '126', '123', '105', '114'],
       ['109', '108', '127', '115', '112', '121', '107', '106'],
       ['121', '129', '129', '102', '113', '100', '111', '100'],
       ['118', '116', '103', '121', '108', '127', '114', '115'],
       ['112', '100', '102', '103', '127', '124', '124', '120'],
       ['125', '115', '113', '113', '117', '119', '102', '107'],
       ['120', '107', '103', '107', '106', '101', '105', '113']],
      dtype='<U11')

In [57]:
# T, F matrix를 이용하여 특정 조건의 데이터를 선택 후 브로드캐스팅하게 값을 대입

In [60]:
result [idx_3] = "fiz"
result [idx_5] = "buz"
result [idx_15] = "fbz"
result

array([['128', '112', 'fiz', 'fiz', '128', 'fiz', '116', 'buz'],
       ['122', 'fiz', '124', '119', 'fiz', 'fiz', 'fbz', 'fiz'],
       ['109', 'fiz', '127', 'buz', '112', '121', '107', '106'],
       ['121', 'fiz', 'fiz', 'fiz', '113', 'buz', 'fiz', 'buz'],
       ['118', '116', '103', '121', 'fiz', '127', 'fiz', 'buz'],
       ['112', 'buz', 'fiz', '103', '127', '124', '124', 'fbz'],
       ['buz', 'buz', '113', '113', 'fiz', '119', 'fiz', '107'],
       ['fbz', '107', '103', '107', '106', '101', 'fbz', '113']],
      dtype='<U11')

# Quiz
- 1 ~ 20까지 랜덤한 숫자를 가지느 5*5 행렬 생성
- 최대값에는 MAX, 최소값에는 MIN 문자열이 들어가도록 치환하는 코드
- 최대값과 최소값 함수

```
np.min(ndarray), np.max(ndarray)
```

In [62]:
datas = np.random.randint(1, 20, (5, 5))
datas

array([[18,  7,  2,  4,  4],
       [12,  8,  6,  8,  1],
       [13, 13,  2, 11, 11],
       [13, 18,  8,  9, 16],
       [ 2,  8, 19,  3,  7]])

In [68]:
idx_min = datas == np.min(datas)
idx_max = datas == np.max(datas)

result = datas.astype("str").copy()
result[idx_min] = "MIN"
result[idx_max] = "MAX"

result

array([['18', '7', '2', '4', '4'],
       ['12', '8', '6', '8', 'MIN'],
       ['13', '13', '2', '11', '11'],
       ['13', '18', '8', '9', '16'],
       ['2', '8', 'MAX', '3', '7']], dtype='<U11')

In [70]:
min_num, max_num = np.min(datas), np.max(datas)
min_num, max_num

(1, 19)

In [71]:
idx_min = datas == min_num
idx_max = datas == max_num

In [73]:
result2 = datas.astype("str")
result2

array([['18', '7', '2', '4', '4'],
       ['12', '8', '6', '8', '1'],
       ['13', '13', '2', '11', '11'],
       ['13', '18', '8', '9', '16'],
       ['2', '8', '19', '3', '7']], dtype='<U11')

In [75]:
result2[idx_min] = "MIN"
result2[idx_max] = "MAX"

result2

array([['18', '7', '2', '4', '4'],
       ['12', '8', '6', '8', 'MIN'],
       ['13', '13', '2', '11', '11'],
       ['13', '18', '8', '9', '16'],
       ['2', '8', 'MAX', '3', '7']], dtype='<U11')

### 1. linspace, logspace 함수
- linspace : 설정한 범위에서 선형적으로 분할한 위치의 값을 출력
- logspace : 설정한 범위에서 로그로 분할한 위치의 값을 출력

In [3]:
# linspace
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [4]:
#logspace
# lgo10(x1) = 2, lgo10(x2) = 3, log10(x3) = 4
np.logspace(2, 4, 3)

array([  100.,  1000., 10000.])

In [ ]:
# 30세에 연봉이 $100000 이고, 60세의 연봉이 $1000000 일때
# 연봉이 선형으로 증가, 지수함수로 증가하는 두 경우에서의 40세, 50세 연봉을 출력

In [5]:
age_30 = 100000
age_60 = 1000000

In [7]:
np.linspace(age_30, age_60, 4) # 여기서 4는 30세 40세 50세 60세를 뜻한다.

array([ 100000.,  400000.,  700000., 1000000.])

In [8]:
np.logspace(np.log10(age_30), np.log10(age_60), 4)

array([ 100000.        ,  215443.46900319,  464158.88336128,
       1000000.        ])

### 2. numpy random
- seed : 랜덤값을 설정값


데이터를 섞는다. 시드가 같으면 랜덤하게 섞이지만, 결과가 같음
섞되 정확도가 바뀌면 안됨 랜덤하게 섞이지만, 동일하게 섞이게 해준다
- rand : 균등분포로 난수를 발생
- randn : 정규분포로 난수를 발생
- randint : 균등분포로 정수값을 발생
- shuffle : 행렬 데이터를 섞어 줍니다
- choice : 특정 확률로 데이터를 선택

In [10]:
# seed
np.random.seed(1)
result1 = np.random.randint(10, 100, 10)

np.random.seed(1)
result2 = np.random.randint(10, 100, 10)

np.random.seed(2)
result3 = np.random.randint(10, 100, 10)

result1, result2, result3

(array([47, 22, 82, 19, 85, 15, 89, 74, 26, 11]),
 array([47, 22, 82, 19, 85, 15, 89, 74, 26, 11]),
 array([50, 25, 82, 32, 53, 92, 85, 17, 44, 59]))

In [11]:
# 0 ~ 1 사이의 숫자, 균등분포로 나옴
np.random.rand(10)

array([0.20464863, 0.61927097, 0.29965467, 0.26682728, 0.62113383,
       0.52914209, 0.13457995, 0.51357812, 0.18443987, 0.78533515])

In [12]:
# 0이랑 가까운 숫자가 나오는 확률이 높게끔 데이터가 뽑힘
np.random.randn(10)

array([-0.0191305 ,  1.17500122, -0.74787095,  0.00902525, -0.87810789,
       -0.15643417,  0.25657045, -0.98877905, -0.33882197, -0.23618403])

In [27]:
# shuffle
r = np.random.randint(1, 10, (3, 4))
r

array([[3, 2, 1, 8],
       [2, 9, 1, 8],
       [1, 6, 3, 6]])

In [28]:
np.random.shuffle(r)
r

array([[3, 2, 1, 8],
       [2, 9, 1, 8],
       [1, 6, 3, 6]])

In [20]:
# choice
np.random.choice(5, 10, p = [0.1, 0, 0.4, 0.2, 0.3])

array([4, 2, 2, 3, 2, 0, 4, 2, 3, 2])

In [30]:
#unique
numbers, counts = np.unique(r, return_counts = True)
print(numbers)
print(counts)

[1 2 3 6 8 9]
[3 2 2 2 2 1]


### 행렬 데이터의 결합
- concatenate

In [33]:
na1 = np.random.randint(10, size=(2, 3))
na2 = np.random.randint(10, size=(3, 2))
na3 = np.random.randint(10, size=(3, 3))

In [34]:
# 세로 결합
na1

array([[3, 3, 1],
       [8, 6, 8]])

In [35]:
na2

array([[1, 5],
       [7, 0],
       [9, 1]])

In [36]:
na3

array([[5, 9, 2],
       [0, 0, 4],
       [6, 3, 1]])

In [40]:
# 세로 결합
np.concatenate((na1, na3))

array([[3, 3, 1],
       [8, 6, 8],
       [5, 9, 2],
       [0, 0, 4],
       [6, 3, 1]])

In [41]:
# 가로 결합
np.concatenate((na2, na3), axis=1)

array([[1, 5, 5, 9, 2],
       [7, 0, 0, 0, 4],
       [9, 1, 6, 3, 1]])

In [42]:
# c_, c_r
np.c_[np.array([1,2,3]), np.array([4,5,6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [43]:
np.r_[np.array([1,2,3]), np.array([4,5,6])]

array([1, 2, 3, 4, 5, 6])

In [44]:
# split, var, std, mean...