# 상관계수 ( Correlation Coefficient )

### Index

1. 분산
1. 공분산
1. 상관계수
1. 결정계수
1. 프리미어리그 데이터 상관계수 분석

In [1]:
import numpy as np

샘플 데이터 생성

In [2]:
data1 = np.array([80, 85, 100, 90, 95])
data2 = np.array([70, 80, 100, 95, 95])

### 2. 분산(variance)
- 1개의 이산정도를 나타냄
- 편차제곱의 평균

$ variance = \frac{\sum_{i=1}^n{(x_i-\bar{x})^2}}{n}, (\bar{x}:평균) $

In [11]:
# variance code
def variance(data):
    
    avg = np.average(data)
    
    tot = 0
    
    for d in data:
        tot += ((d - avg)**2) 
    
    return tot/len(data)

In [16]:
# standard variation = var ** 0.5
variance(data1), variance(data2), variance(data1)**0.5, variance(data2)**0.5

(50.0, 126.0, 7.0710678118654755, 11.224972160321824)

In [17]:
np.var(data1), np.var(data2), np.std(data1), np.std(data2)

(50.0, 126.0, 7.0710678118654755, 11.224972160321824)

일반 함수와 numpy 함수의 퍼포먼스 비교

In [20]:
p_data1 = np.random.randint(60, 100, int(1E5))
p_data2 = np.random.randint(60, 100, int(1E5))

In [22]:
# 일반함수

In [23]:
%%time
variance(p_data1), variance(p_data2)

Wall time: 702 ms


(133.20338241912714, 132.72529838710156)

In [24]:
#numpy

In [25]:
%%time
np.var(p_data1), np.var(p_data2)

Wall time: 2 ms


(133.2033824191, 132.72529838710003)

### 3. 공분산(covariance)
- 2개의 확률변수의 상관정도를 나타냄
- 평균 편차곱
- 방향성은 보여줄수 있으나 강도를 나타내는데 한계가 있다
    - 표본데이터의 크기에 따라서 값의 차이가 큰 단점이 있다
    
- 두개의 데이터가 같이 움직이는지
     - 올라갈 때 같이 올라가고 떨어질 때 같이 떨어지는지 (+)
     - 하나가 올라갈 떄 다른 하나는 떨어지는지 (-)
     - 2개의 확률변수의 상관정도를 알수 있음

$ covariance = \frac{\sum_{i=1}^{n}{(x_i-\bar{x})(y_i-\bar{y})}}{n}, (\bar{x}:x의 평균, \bar{y}:y의 평균) $

In [26]:
# covariance function

In [27]:
data1 = np.array([80, 85, 100, 90, 95])
data2 = np.array([70, 80, 100, 95, 95])
np.cov(data1, data2)

array([[ 62.5 ,  93.75],
       [ 93.75, 157.5 ]])

```
array([[data1&data1, data1&data2],
       [data2&data1, data2&data2]])
```

In [34]:
 np.cov(data1, data2)[0, 1] # 올라갈 떄 같이, 떨어질 때 같이

93.75

In [31]:
data3 = np.array([80, 85, 100, 90, 95])
data4 = np.array([100, 90, 70, 90, 80])
np.cov(data3, data4)

array([[ 62.5, -87.5],
       [-87.5, 130. ]])

In [35]:
np.cov(data3, data4)[0, 1] # 올라갈 때 떨어지고, 떨어질 때 올라감

-87.5

In [38]:
# 위 데이터와 움직이는 정도가 비슷하지만, 스케일만 커짐
# 하지만 스케일이 커짐으로서 값도 증가함
# 값이 어느정도 간격이 있는지 나타내는데 한계가 있음
data5 = np.array([800, 850, 1000, 900, 950])
data6 = np.array([1000, 900, 700, 900, 800])
np.cov(data3, data4)[0, 1]

-8750.0

### 4. 상관계수(correlation coefficient)
- 공분산의 한계를 극복하기 위해서 만들어짐
- -1 ~ 1까지의 수를 가지며 0과 가까울수록 상관도가 적음을 의미
- x의 분산과 y의 분산을 곱한 결과의 제곱근을 나눠주면 x나 y의 변화량이 클수록 0에 가까워짐
- https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.corrcoef.html
- 0하고 가까울수록 두개가 관련이 없다는 뜻
- 1하고 가까울수록 두개가 같이 움직인다는 뜻
- -1하고 가까울수록 두개가 반대로 움직인다는 뜻

$ correlation-coefficient = \frac{공분산}{\sqrt{{x분산} \cdot {y분산}}} $

최종 상관계수

$ r = \frac{\sum(x-\bar{x})(y-\bar{y})}{\sqrt{{\sum(x-\bar{x})^2}\cdot{\sum(y-\bar{y})^2}}} $

In [40]:
# correlation coefficient function
np.corrcoef(data1, data2)[0,1], \
np.corrcoef(data3, data4)[0,1], \
np.corrcoef(data5, data6)[0,1]

(0.9449111825230682, -0.970725343394151, -0.970725343394151)

data1을 예측하기 위해서는 data2 or data4 사용하는게 좋을지?
- data4를 사용하는게 좋다
- 반대로 움직이지만, 두개가 더 큰 관계를 갖는다
- 이 관계를 +-를 없애서 계산을 해서 수치화 시켜준게 결정계수

### 5. 결정계수(cofficient of determination: R-squared)
- x로부터 y를 예측할수 있는 정도
- 상관계수의 제곱 (상관계수를 양수화)
- 수치가 클수록 회기분석을 통해 예측할수 있는 수치의 정도가 더 정확

In [42]:
np.corrcoef(data1, data2)[0, 1] ** 2, \
np.corrcoef(data1, data4)[0, 1] ** 2

(0.892857142857143, 0.9423076923076923)

### 6. 프리미어리그 데이터 상관계수 분석
- 2016년 프리미어리그 성적에서 득점과 실점 데이터중에 승점에 영향을 더 많이 준 데이터는?

In [43]:
import pandas as pd

ModuleNotFoundError: No module named 'pandas'

In [44]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [45]:
import pandas as pd

In [46]:
!ls datas

premierleague.csv


In [47]:
df = pd.read_csv("datas/premierleague.csv")
df.tail()

name  gf  ga  points
15     Huddersfield Town  28  58      37
16           Southampton  37  56      36
17          Swansea City  28  56      33
18            Stoke City  35  68      33
19  West Bromwich Albion  31  56      31

In [48]:
# 득점
gf = np.array(df["gf"])
gf

array([106,  68,  74,  84,  62,  74,  36,  44,  56,  39,  45,  45,  48,
        44,  34,  28,  37,  28,  35,  31], dtype=int64)

In [52]:
# 실점
ga = np.array(df["ga"])
ga

array([27, 28, 36, 38, 38, 51, 39, 58, 60, 47, 55, 61, 68, 64, 54, 58, 56,
       56, 68, 56], dtype=int64)

In [53]:
# 승점
points = np.array(df["points"])
points

array([100,  81,  77,  75,  70,  63,  54,  49,  47,  44,  44,  44,  42,
        41,  40,  37,  36,  33,  33,  31], dtype=int64)

In [55]:
np.cov(gf, points)[0, 1], np.cov(ga, points)[0, 1]

(374.58421052631564, -208.10000000000002)

In [56]:
np.corrcoef(gf, points)[0, 1], np.corrcoef(ga, points)[0, 1]

(0.9318404636463514, -0.8705940043262674)

In [59]:
data1, data2 = np.corrcoef(gf, points)[0, 1]**2, np.corrcoef(ga, points)[0, 1]**2
data1, data2

(0.8683266496886471, 0.757933920368845)

In [60]:
round(data1, 2), round(data2, 2)

(0.87, 0.76)