### 타이타닉 생존자 예측 모델 만들기

- 데이터 수집
- 데이터 전처리
- 데이터 분석 및 모델링
- 결론 및 모델 평가

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [6]:
!pip install sklearn

^C


In [3]:
# 1. 데이터 수집
titanic = pd.read_csv("train.csv")
titanic.tail(1)

PassengerId  Survived  Pclass                 Name   Sex   Age  SibSp  \
890          891         0       3  Dooley, Mr. Patrick  male  32.0      0   

     Parch  Ticket  Fare Cabin Embarked  
890      0  370376  7.75   NaN        Q

In [4]:
# 2. 데이터 전처리 1
titanic_1 = titanic[["Pclass", "Age", "SibSp", "Parch", "Fare", "Survived"]]
titanic_1.dropna(inplace=True)
titanic_1.reset_index(drop=True, inplace=True)
titanic_1.tail(1)

C:\Users\Gk\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


Pclass   Age  SibSp  Parch  Fare  Survived
713       3  32.0      0      0  7.75         0

In [5]:
titanic_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 714 entries, 0 to 713
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Pclass    714 non-null    int64  
 1   Age       714 non-null    float64
 2   SibSp     714 non-null    int64  
 3   Parch     714 non-null    int64  
 4   Fare      714 non-null    float64
 5   Survived  714 non-null    int64  
dtypes: float64(2), int64(4)
memory usage: 33.6 KB


In [6]:
# 데이터셋 분리
df_x = titanic_1.drop(columns=["Survived"])
df_y = titanic_1["Survived"]
train_x, test_x, train_y, test_y = train_test_split(df_x, df_y, test_size=0.2,random_state=1)
len(train_x), len(test_x), len(train_y), len(test_y)

(571, 143, 571, 143)

In [7]:
train_x

Pclass   Age  SibSp  Parch     Fare
663       3  15.0      1      0  14.4542
447       3  24.0      2      0  24.1500
119       2  36.5      0      2  26.0000
82        3  28.0      0      0   7.8958
233       3  22.0      0      0   7.7500
..      ...   ...    ...    ...      ...
144       3  36.0      0      0   0.0000
645       2  39.0      0      0  13.0000
72        3  26.0      1      2  20.5750
235       1  19.0      1      0  91.0792
37        3  21.0      0      0   7.8000

[571 rows x 5 columns]

In [8]:
# 3. 모델링 : DecisionTree, Support Vector Machine

In [9]:
# DecisionTree
from sklearn.tree import DecisionTreeClassifier

In [10]:
model_1 = DecisionTreeClassifier(random_state=1)
model_1.fit(train_x, train_y) # 학습 : 가중치 계산

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=1, splitter='best')

In [11]:
pred_y = model_1.predict(test_x)

In [12]:
y = np.array(test_y)

In [13]:
y

array([1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0], dtype=int64)

In [117]:
pred_y

array([1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0], dtype=int64)

In [101]:
len(y[y == pred_y]) / len(pred_y)

0.6853146853146853

In [102]:
model_1.score(test_x, test_y)

0.6853146853146853

In [14]:
# SVM
from sklearn.svm import SVC

In [16]:
model_2 = SVC()
model_2.fit(train_x, train_y) # 학습 : 가중치 계산

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [17]:
pred_y = model_2.predict(test_x)

In [18]:
model_2.score(test_x, test_y)

0.6783216783216783

In [ ]:
# dataset 1 : 68.53% / 67.83

In [19]:
# 2. 데이터 전처리 2

onehot_sex = pd.get_dummies(titanic["Sex"])
onehot_embark = pd.get_dummies(titanic["Embarked"])

titanic_2 = titanic[["Pclass", "Age", "SibSp", "Parch", "Fare", "Survived"]]
titanic_2 = pd.concat([titanic_2, onehot_sex, onehot_embark], axis = 1)
titanic_2

Pclass   Age  SibSp  Parch     Fare  Survived  female  male  C  Q  S
0         3  22.0      1      0   7.2500         0       0     1  0  0  1
1         1  38.0      1      0  71.2833         1       1     0  1  0  0
2         3  26.0      0      0   7.9250         1       1     0  0  0  1
3         1  35.0      1      0  53.1000         1       1     0  0  0  1
4         3  35.0      0      0   8.0500         0       0     1  0  0  1
..      ...   ...    ...    ...      ...       ...     ...   ... .. .. ..
886       2  27.0      0      0  13.0000         0       0     1  0  0  1
887       1  19.0      0      0  30.0000         1       1     0  0  0  1
888       3   NaN      1      2  23.4500         0       1     0  0  0  1
889       1  26.0      0      0  30.0000         1       0     1  1  0  0
890       3  32.0      0      0   7.7500         0       0     1  0  1  0

[891 rows x 11 columns]

In [20]:
# none 데이터를 다 제거해야함. 그렇지 않으면 모델링 시 에러
titanic_2.dropna(inplace=True)
titanic_2.reset_index(drop=True, inplace=True)
titanic_2.tail(1)

Pclass   Age  SibSp  Parch  Fare  Survived  female  male  C  Q  S
713       3  32.0      0      0  7.75         0       0     1  0  1  0

In [21]:
# 데이터셋 분리

df_x = titanic_2.drop(columns=["Survived"])
df_y = titanic_2["Survived"]
train_x, test_x, train_y, test_y = train_test_split(df_x, df_y, test_size=0.2,random_state=1)
len(train_x), len(test_x), len(train_y), len(test_y)

(571, 143, 571, 143)

In [22]:
model_1 = DecisionTreeClassifier(random_state=1)
model_1.fit(train_x, train_y) # 학습 : 가중치 계산

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=1, splitter='best')

In [23]:
pred_y = model_1.predict(test_x)

In [24]:
y = np.array(test_y)

In [25]:
y

array([1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0], dtype=int64)

In [26]:
pred_y

array([1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0], dtype=int64)

In [27]:
len(y[y == pred_y]) / len(pred_y)

0.8251748251748252

In [28]:
model_1.score(test_x, test_y)

0.8251748251748252

In [29]:
model_2 = SVC()
model_2.fit(train_x, train_y) # 학습 : 가중치 계산

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [30]:
pred_y = model_2.predict(test_x)

In [31]:
model_2.score(test_x, test_y)

0.6853146853146853