# 수학 기초

## Day 3 선형대수

In [1]:
import numpy as np

In [2]:
a = np.array([1, 1])

In [3]:
print(a)

[1 1]


In [4]:
b = np.array([-1, 1])

In [5]:
print(b)

[-1  1]


In [6]:
a + b

array([0, 2])

In [7]:
a - b

array([2, 0])

In [8]:
c = [1, 1]
d = [-1, 1]
c + d

[1, 1, -1, 1]

In [9]:
a * 0

array([0, 0])

In [10]:
a* 2

array([2, 2])

In [11]:
b * 2

array([-2,  2])

In [12]:
(a + b) *2

array([0, 4])

In [13]:
a*2 + b*2

array([0, 4])

In [14]:
a*(2+3)

array([5, 5])

In [15]:
a*2 + a*3

array([5, 5])

In [16]:
def vectorInnerProd(x,y):
    return sum(x*y)

In [17]:
vectorInnerProd(a, b)

0

In [18]:
np.dot(a, b)

0

In [19]:
def vectorLength(x):
    return sum(x**2)**(1/2)

In [20]:
vectorLength(a)

1.4142135623730951

In [21]:
np.dot(a, a)**(1/2)

1.4142135623730951

In [22]:
vectorInnerProd(a, b) / (vectorLength(a) * vectorLength(b))

0.0

In [23]:
A = np.array([[1,2], [3,4]])

In [24]:
A

array([[1, 2],
       [3, 4]])

In [25]:
B = np.array([[4,3],[2,1]])

In [26]:
B

array([[4, 3],
       [2, 1]])

In [28]:
C = np.ones([2,2])
C

array([[1., 1.],
       [1., 1.]])

In [29]:
O = np.zeros([2,2])
O

array([[0., 0.],
       [0., 0.]])

In [30]:
A + B

array([[5, 5],
       [5, 5]])

In [31]:
B + A

array([[5, 5],
       [5, 5]])

In [32]:
(A + B) + C

array([[6., 6.],
       [6., 6.]])

In [33]:
A + (B + C)

array([[6., 6.],
       [6., 6.]])

In [34]:
A * 0

array([[0, 0],
       [0, 0]])

In [35]:
A * 2

array([[2, 4],
       [6, 8]])

In [36]:
B * 2

array([[8, 6],
       [4, 2]])

In [37]:
A*2 + B*2

array([[10, 10],
       [10, 10]])

In [38]:
(A + B) * 2

array([[10, 10],
       [10, 10]])

In [39]:
A * (2+3)

array([[ 5, 10],
       [15, 20]])

In [40]:
A*2 + A*3

array([[ 5, 10],
       [15, 20]])

In [41]:
np.matmul(A,B)

array([[ 8,  5],
       [20, 13]])

In [42]:
np.matmul(B, A)

array([[13, 20],
       [ 5,  8]])

In [43]:
import numpy.linalg as lin

In [44]:
AI = lin.inv(A)

In [45]:
AI

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [46]:
np.matmul(A,AI)

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [47]:
np.matmul(AI, A)

array([[1.0000000e+00, 4.4408921e-16],
       [0.0000000e+00, 1.0000000e+00]])

In [48]:
lin.det(A)

-2.0000000000000004

In [49]:
lin.det(B)

-2.0

In [51]:
M = np.array([[1,2], [2,4]])

In [52]:
lin.det(M)

0.0